<a href="https://colab.research.google.com/github/Vengalagagan/NLP/blob/main/2403A52222(B_09)NLP_Lab_15_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [31]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np

Load ELMO Model

In [32]:
elmo = hub.load("https://tfhub.dev/google/elmo/3")

Text Corpus(Documents)

In [40]:
sentences = [
    "The bank will not approve the loan",
    "He sat on the river bank",
    "She deposited money in the bank",
    "Children played near the bank of the lake",
    "The company borrowed funds from the bank",
    "The fisherman stood quietly on the bank",
    "The bank offers low interest rates",
    "Flowers were growing along the river bank"
]

Embeddings

In [39]:
embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']
print(embeddings.shape)

(8, 8, 1024)


Word Embedding (“bank”)

In [37]:
# Convert sentences into tokens
tokenized = [sentence.split() for sentence in sentences]

# Find index of "bank" in every sentence
bank_indices = [tokens.index("bank") for tokens in tokenized]

# Extract embeddings of "bank" from all sentences
bank_embeddings = [
    embeddings[i][bank_indices[i]]
    for i in range(len(sentences))
]

# Print first 10 values for each sentence
for i, emb in enumerate(bank_embeddings):
    print(f"Sentence {i+1}: {sentences[i]}")
    print("First 10 values:", emb[:10])
    print()

Sentence 1: The bank will not approve the loan
First 10 values: tf.Tensor(
[-0.9086766  -0.36578724 -0.0733975   0.5866749   0.22132955 -0.7657322
 -0.11816446 -0.3022788  -0.06137528  0.16951814], shape=(10,), dtype=float32)

Sentence 2: He sat on the river bank
First 10 values: tf.Tensor(
[-0.15614772  0.28345677 -0.08914644  0.20695065  0.15241832 -0.20373058
 -0.10812794  0.03747281  0.52148664  0.353526  ], shape=(10,), dtype=float32)

Sentence 3: She deposited money in the bank
First 10 values: tf.Tensor(
[-0.33989906  0.34286597 -0.07132763  0.36118096 -0.28549266 -0.31172186
 -0.41095564 -0.11300926  0.03143679  0.57589567], shape=(10,), dtype=float32)

Sentence 4: Children played near the bank of the lake
First 10 values: tf.Tensor(
[-0.63130385  0.36684275 -0.50689137  0.06840359 -0.14123407  0.04119962
 -0.29742515  0.08263844  0.69130445  0.03459672], shape=(10,), dtype=float32)

Sentence 5: The company borrowed funds from the bank
First 10 values: tf.Tensor(
[-0.49415144 -

Cosine Similarity

In [38]:
import numpy as np

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# Compare all bank embeddings with each other
for i in range(len(bank_embeddings)):
    for j in range(i + 1, len(bank_embeddings)):
        sim = cosine_similarity(
            bank_embeddings[i].numpy(),
            bank_embeddings[j].numpy()
        )
        print(f"Similarity between Sentence {i+1} and Sentence {j+1}: {sim:.4f}")

Similarity between Sentence 1 and Sentence 2: 0.5781
Similarity between Sentence 1 and Sentence 3: 0.6263
Similarity between Sentence 1 and Sentence 4: 0.6505
Similarity between Sentence 1 and Sentence 5: 0.6395
Similarity between Sentence 1 and Sentence 6: 0.5818
Similarity between Sentence 1 and Sentence 7: 0.9374
Similarity between Sentence 1 and Sentence 8: 0.5703
Similarity between Sentence 2 and Sentence 3: 0.7751
Similarity between Sentence 2 and Sentence 4: 0.6787
Similarity between Sentence 2 and Sentence 5: 0.7241
Similarity between Sentence 2 and Sentence 6: 0.8938
Similarity between Sentence 2 and Sentence 7: 0.5951
Similarity between Sentence 2 and Sentence 8: 0.9196
Similarity between Sentence 3 and Sentence 4: 0.6517
Similarity between Sentence 3 and Sentence 5: 0.8805
Similarity between Sentence 3 and Sentence 6: 0.7599
Similarity between Sentence 3 and Sentence 7: 0.6456
Similarity between Sentence 3 and Sentence 8: 0.7728
Similarity between Sentence 4 and Sentence 5: 